_format_version: "3.0"
_transform: true

services:
  # Auth
  - name: auth-v1
    url: http://auth:9999
    routes:
      - name: auth-v1-all
        strip_path: true
        paths: [ /auth/v1/ ]

  # REST
  - name: rest-v1
    url: http://rest:3000
    routes:
      - name: rest-v1-all
        strip_path: false
        paths: [ /rest/v1/ ]

  # Realtime
  - name: realtime-v1
    url: http://realtime:4000/socket
    routes:
      - name: realtime-v1-all
        strip_path: true
        paths: [ /realtime/v1/ ]

  # Storage
  - name: storage-v1
    url: http://storage:5000
    routes:
      - name: storage-v1-all
        strip_path: false
        paths: [ /storage/v1/ ]

  # Health‑check especial para o próprio Kong
  - name: kong-health
    url: http://localhost:8001/status
    routes:
      - name: kong-health-route
        paths: [ /health ]
